@startuml

title __BALLS's Class Diagram__\n

  namespace ru.gb.jtwo.lone.online {
    namespace circles.balls {
      class ru.gb.jtwo.lone.online.circles.balls.Background {
          {static} - AMPLITUDE : float
          - color : Color
          - time : float
          + render()
          + update()
      }
    }
  }
  

  namespace ru.gb.jtwo.lone.online {
    namespace circles.balls {
      class ru.gb.jtwo.lone.online.circles.balls.Ball {
          - color : Color
          - vX : float
          - vY : float
          + render()
          + update()
          ~ Ball()
          ~ Ball()
      }
    }
  }
  

  namespace ru.gb.jtwo.lone.online {
    namespace circles.balls {
      class ru.gb.jtwo.lone.online.circles.balls.MainCircles {
          {static} - POS_X : int
          {static} - POS_Y : int
          {static} - WINDOW_HEIGHT : int
          {static} - WINDOW_WIDTH : int
          - gameObjects : GameObject[]
          - gameObjectsCount : int
          {static} + main()
          + onDrawFrame()
          - MainCircles()
          - addGameObject()
          - initApplication()
          - removeGameObject()
          - render()
          - update()
      }
    }
  }
  

  ru.gb.jtwo.lone.online.circles.balls.Background .up.|> ru.gb.jtwo.lone.online.circles.common.GameObject
  ru.gb.jtwo.lone.online.circles.balls.Ball -up-|> ru.gb.jtwo.lone.online.circles.common.Sprite
  ru.gb.jtwo.lone.online.circles.balls.MainCircles .up.|> ru.gb.jtwo.lone.online.circles.common.CanvasListener
  ru.gb.jtwo.lone.online.circles.balls.MainCircles -up-|> javax.swing.JFrame


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
