@startuml

title __BRICKS's Class Diagram__\n

  namespace ru.gb.jtwo.lone.online {
    namespace circles.bricks {
      class ru.gb.jtwo.lone.online.circles.bricks.Background {
          - color : Color
          + render()
          + update()
      }
    }
  }
  

  namespace ru.gb.jtwo.lone.online {
    namespace circles.bricks {
      class ru.gb.jtwo.lone.online.circles.bricks.Brick {
          - color : Color
          - vX : float
          - vY : float
          + render()
          + update()
          ~ Brick()
          ~ Brick()
      }
    }
  }
  

  namespace ru.gb.jtwo.lone.online {
    namespace circles.bricks {
      class ru.gb.jtwo.lone.online.circles.bricks.MainBricks {
          {static} - POS_X : int
          {static} - POS_Y : int
          {static} - WINDOW_HEIGHT : int
          {static} - WINDOW_WIDTH : int
          - gameObjects : GameObject[]
          - gameObjectsCount : int
          {static} + main()
          + onDrawFrame()
          - MainBricks()
          - addGameObject()
          - initApplication()
          - removeGameObject()
          - render()
          - update()
      }
    }
  }
  

  ru.gb.jtwo.lone.online.circles.bricks.Background .up.|> ru.gb.jtwo.lone.online.circles.common.GameObject
  ru.gb.jtwo.lone.online.circles.bricks.Brick -up-|> ru.gb.jtwo.lone.online.circles.common.Sprite
  ru.gb.jtwo.lone.online.circles.bricks.MainBricks .up.|> ru.gb.jtwo.lone.online.circles.common.CanvasListener
  ru.gb.jtwo.lone.online.circles.bricks.MainBricks -up-|> javax.swing.JFrame


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
