@startuml

title __ONLINE's Class Diagram__\n

  namespace ru.gb.jtwo.ltwo.online {
    interface ru.gb.jtwo.ltwo.online.Animal {
        {abstract} + breathe()
        {abstract} + look()
    }
  }
  

  namespace ru.gb.jtwo.ltwo.online {
    interface ru.gb.jtwo.ltwo.online.Bull {
        {abstract} + voice()
        + walk()
    }
  }
  

  namespace ru.gb.jtwo.ltwo.online {
    interface ru.gb.jtwo.ltwo.online.Human {
        {abstract} + talk()
        {abstract} + walk()
    }
  }
  

  namespace ru.gb.jtwo.ltwo.online {
    class ru.gb.jtwo.ltwo.online.Main {
        {static} + main()
        {static} - addKeyboardListener()
        {static} - interfaceExample()
        {static} - methodA()
    }
  }
  

  namespace ru.gb.jtwo.ltwo.online {
    class ru.gb.jtwo.ltwo.online.Main.IOStream {
        ~ fnfe : FileNotFoundException
        ~ ioew : SQLException
        + close()
        + open()
        + write()
    }
  }
  

  namespace ru.gb.jtwo.ltwo.online {
    abstract class ru.gb.jtwo.ltwo.online.Main.KeyboardAdapter {
        + keyPressed()
    }
  }
  

  namespace ru.gb.jtwo.ltwo.online {
    interface ru.gb.jtwo.ltwo.online.Main.KeyboardListener {
        {abstract} + keyPressed()
    }
  }
  

  namespace ru.gb.jtwo.ltwo.online {
    class ru.gb.jtwo.ltwo.online.Minotaur {
        + breathe()
        + look()
        + talk()
        + voice()
        + walk()
    }
  }
  

  ru.gb.jtwo.ltwo.online.Main +-down- ru.gb.jtwo.ltwo.online.Main.IOStream
  ru.gb.jtwo.ltwo.online.Main +-down- ru.gb.jtwo.ltwo.online.Main.KeyboardAdapter
  ru.gb.jtwo.ltwo.online.Main +-down- ru.gb.jtwo.ltwo.online.Main.KeyboardListener
  ru.gb.jtwo.ltwo.online.Main.IOStream .up.|> java.io.Closeable
  ru.gb.jtwo.ltwo.online.Main.KeyboardAdapter .up.|> ru.gb.jtwo.ltwo.online.Main.KeyboardListener
  ru.gb.jtwo.ltwo.online.Minotaur .up.|> ru.gb.jtwo.ltwo.online.Bull
  ru.gb.jtwo.ltwo.online.Minotaur .up.|> ru.gb.jtwo.ltwo.online.Human


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
