@startuml

title __COMMON's Class Diagram__\n

  namespace ru.gb.jtwo.lone.online {
    namespace circles.common {
      interface ru.gb.jtwo.lone.online.circles.common.CanvasListener {
          {abstract} + onDrawFrame()
      }
    }
  }
  

  namespace ru.gb.jtwo.lone.online {
    namespace circles.common {
      class ru.gb.jtwo.lone.online.circles.common.GameCanvas {
          ~ lastFrameTime : long
          + GameCanvas()
          + getBottom()
          + getLeft()
          + getRight()
          + getTop()
          # paintComponent()
      }
    }
  }
  

  namespace ru.gb.jtwo.lone.online {
    namespace circles.common {
      interface ru.gb.jtwo.lone.online.circles.common.GameObject {
          {abstract} + render()
          {abstract} + update()
      }
    }
  }
  

  namespace ru.gb.jtwo.lone.online {
    namespace circles.common {
      class ru.gb.jtwo.lone.online.circles.common.Sprite {
          # halfHeight : float
          # halfWidth : float
          # x : float
          # y : float
          + render()
          + update()
          # getBottom()
          # getHeight()
          # getLeft()
          # getRight()
          # getTop()
          # getWidth()
          # setBottom()
          # setLeft()
          # setRight()
          # setTop()
      }
    }
  }
  

  ru.gb.jtwo.lone.online.circles.common.GameCanvas -up-|> javax.swing.JPanel
  ru.gb.jtwo.lone.online.circles.common.GameCanvas o-- ru.gb.jtwo.lone.online.circles.common.CanvasListener : gameController
  ru.gb.jtwo.lone.online.circles.common.Sprite .up.|> ru.gb.jtwo.lone.online.circles.common.GameObject


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
